language: go

go:
    - 1.6
    - tip

before_install:
    - go get github.com/golang/lint/golint
    - go get github.com/mattn/goveralls

script:
    - go test -bench=. -benchmem ./...
    #- sh ./install_all_cmd.sh
